### ISSUE TITLE
Carrello

### ISSUE THREAD

**Issue by GiuSeppE898** [thatsfaso/NewAgain#3]
- [x] Aggiustare tasti conferma di altro indirizzo e carta di credito per far si che confermando non faccia redirect altrove, ma aggiorna la riga che gli riguarda
- [x] Banner/Pagina successiva di riepilogo ordine + tasto "Acquista Ora" (E poi fa redirect alla home dove esce un banner che dice che è stata inviata ad "email" la mail con la fattura e dettagli ordine)
- [x] Tasto cancella vicino ai prodotti
- [x] Tasto sotto tutta la lista prodotti "Cancella Carrello" che svuota il carrello
- [x] Conferma più sotto del form di pagamento carta di credito
- [x] Eliminazione Quantità

**Comment by thatsfaso** [comment]
CSS side 

- [x] Confirmation page
![Senza titolo-1](https://github.com/thatsfaso/NewAgain/assets/127889824/474fbb17-30aa-4ae7-81a9-0079a7610a8e)
