### ISSUE TITLE
Pagina Amministratore

### ISSUE THREAD

**Issue by GiuSeppE898** [thatsfaso/NewAgain#4]
- [x] Pagina con design simile/o uguale a AreaUtente dove ci sono 3 sottopagine, la prima dove c'è l'intero catalogo dei prodotti dove può modificare/cancellare ogni prodotto e alla fine c'è l'insert, la seconda dove c'è la lista degli utenti + barra di ricerca affianco al titolo, la terza lista ordini dove può fare il sort per data + barra ricerca cliente 
- [x] requisiti: admin.jsp (Pagina di controllo), AdminControl(Servlet che esegue le operazioni):
Visualizzare gli ordini di tutti i clienti, per cliente e dalla data alla data.
L'amministratore deve poter vedere l'elenco degli utenti e ricercare un utente specifico
Inserire prodotti nel catalogo
 AmministratoreDao che contiene le query per eseguire le operazioni sopra citate

**Comment by thatsfaso** [comment]
TO BE FIXED
- [x] Manca un testo di reset in entrambe le barre di ricerca che, dopo aver ricercato un utente, vorrei resettare la ricerca e riavere tutta la lista completa di ordini/utenti per ricercare altro (senza ricaricare la pagina), anche perchè se riclicco su Lista Ordini non succede niente quindi non c'è nessun modo per ora per riavere la tabella completa (nemmeno facendo backpage) 
- [x] Corpo (tabella sopratutto) di lista ordini troppo sulla destra, non è centrale 
- [x] Insert
- [x] Modifica
- [x] Cancellazione
- [x] Tasti in azioni di prodotti da aggiustare

**Comment by thatsfaso** [comment]
- [x] Come query delle barre di ricerca usare la funzione "like" per far si che in caso di errore di battitura il risultato più vicino esca lo stesso

**Comment by thatsfaso** [comment]
- [x] Aggiustare il lato responsive della pagina
- [x] Mettere la tabella ORDINI più a sinistra 
- [x] Nella tabella prodotti Quantità deve passare a Disponibilità
- [x] Aggiustare il banner come in foto...

<img width="741" alt="Schermata 2023-06-02 alle 03 30 47" src="https://github.com/thatsfaso/NewAgain/assets/127889824/725c4b46-7c2a-40bf-8d54-08edf0136ef2">
<img width="796" alt="Schermata 2023-06-02 alle 03 32 51" src="https://github.com/thatsfaso/NewAgain/assets/127889824/5dbe94d4-9017-474e-8acc-7c937ebbb34c">
<img width="179" alt="Schermata 2023-06-02 alle 03 33 27" src="https://github.com/thatsfaso/NewAgain/assets/127889824/86764415-dac9-4d8e-9309-528abe1c24b7">
