### ISSUE TITLE
Profilo

### ISSUE THREAD

**Issue by GiuSeppE898** [thatsfaso/NewAgain#5]
- [x] Pagina I Miei Ordini -> aggiunta alla tabella di un tasto "Dettagli", che se cliccato mostra i prodotti acquistati riguardo quel relativo ordine

**Comment by thatsfaso** [comment]
- [x] Tabella i miei ordini farla con lo stesso design di "I miei dati" con la tabella leggermente più grande
- [x] In "I miei ordini" se clicco mostra fa redirect a i miei dati, e mostra deve fare in modo che se riclicco si chiude il mostra
- [x] In "I miei ordini" affianco a dettagli dev'esserci un'altra colonna chiamata "Ricevuta" che al click di "Visualizza" apre la pagina in un altro pannello (non finestra) e visualizza il pdf (già menzionato in [Fattura](https://github.com/thatsfaso/NewAgain/issues/13)) - ovviamente se viene fatta questa task prima della fattura va bene se mettete come href google.it poi si integra la fattura in secondo momento
- [x] In i miei dati, Email va sopra a password e gli altri salgono di conseguenza
- [x] profilo utente e anche i miei dati decisamente meno anonime come pagine pls, vi mostro nell'allegato
- [x] aggiustare la responsiveness perchè se stringo un po' la tabella scende a fondo pagina quasi
- [x] Nella tabella i miei ordini "Dettagli" della tabella dettagli deve chiamarsi "Mostra" o "Mostra Dettagli"

<img width="726" alt="Schermata 2023-06-02 alle 03 48 04" src="https://github.com/thatsfaso/NewAgain/assets/127889824/262dfef0-69cb-448f-bcc9-baafcc73a789">
<img width="631" alt="Schermata 2023-06-02 alle 03 52 56" src ="https://github.com/thatsfaso/NewAgain/assets/127889824/55d48436-12ba-4287-b106-4f3c5c2be5ed">
<img width="1266" alt="Schermata 2023-06-02 alle 03 52 12 copia" src="https://github.com/thatsfaso/NewAgain/assets/127889824/3d24f6d8-7c4a-475d-ad23-a7da83c6da53">
